### PR TITLE
add screenshot-based record mode to save resources and improve controllability

### PR DESCRIPTION
**Pull request by Antonoko**
todo:
- [x] 用持续、间隔的截图行为来替代 ffmpeg 录屏
    - [x] 可配置项：
        - 截图间隔时间（透传）
        - 截图相似度、OCR 文本相似度、单个视频时长（隐式）
           - 通过阈值决定是否将内存截图持久为文件
    - [x] 模式选择：全范围截图/仅截取前台窗口
    - [x] 窗口裁剪范围
    - [x] 临时数据结构设计：保存截图名、时间戳、OCR 结果等信息，存放路径结构设计
        - [x] 沿用数据项去重操作配置
        - [x] 持久化写入sqlite数据库
    - [x] 合成视频
        - [x] ffmpeg R&D 
        - [x] 测算最大图片尺寸，作为视频的最大尺寸
        - [x] 二次压制优化视频体积
        - [x] 边缘情况处理：如截图数量不足
        - [x] 可选项：在闲时或插入电源时合成
- [x] 即时回放：在被转换为视频之前，可以在 webui 中时间轴回顾尝试定位到截图（查找最近的一张缓存图，判断是否超过?s的阈值范围）
   - [x] 优化图片显示效果
- [x] 延时回放：定位到已合并压缩后的视频
- [x] 保留截图缓存，兼容图像语义识别
- [x] UI setting
- [x] polish & test

### CODE REVIEW

**Comment by morningstar2213** [comment]
Can you make the decision optional man? To alterate or choose between video or screenshot processes.

**Comment by Antonoko** [comment]
> Can you make the decision optional man? To alterate or choose between video or screenshot processes.

yes of course, this will be forward compatible with two selectable recording modes, allowing you to continue with previous video recording or choose more targeted screenshot recording.

**Comment by morningstar2213** [comment]
> > Can you make the decision optional man? To alterate or choose between video or screenshot processes.
> 
> yes of course, this will be forward compatible with two selectable recording modes, allowing you to continue with previous video recording or choose more targeted screenshot recording.

Aye man thank you so much. Love the DLC pack. Keep going broski.

**Comment by morningstar2213** [comment]
I love the Youtube timeline scrubbing when watching a video.
Has a filmstrip feel to it, where I can scrub or just seek any moment within that video. 
Any see each frame also frame by frame in that video. 

Think this would be another cool feature to look into, of course when permitting. 

Take care guys. 

https://tomashubelbauer.github.io/html-video-scrubber/

**Comment by morningstar2213** [comment]
image
image


It works in the way that allows you to push up on the scrollbar when you click on it - for Youtube that is.

**Comment by morningstar2213** [comment]
https://clipchamp.com/en/blog/video-scrubbing/
https://github.com/IsabelleBaker/FrameGrabber
https://github.com/abhishekcghosh/experiment-video-scrub
https://github.com/tlecoz/Mp4Maker
https://github.com/cawa-93/youtube-forward-timeline
https://github.com/Sriver27/YouTube-Timeline-Bookmarker



This is great too, compliments lightbox feature.
https://video-scrub.playground.ghosh.dev/frame-extract-tool/

**Comment by Antonoko** [comment]
> I love the Youtube timeline scrubbing when watching a video. Has a filmstrip feel to it, where I can scrub or just seek any moment within that video. Any see each frame also frame by frame in that video.

Thanks for your suggestions and deep research! They all look super dope and creative. I will filed them in an issue. (hope one day noob like me would realize some of these ideas...

**Pull request merged**
